// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48OCl9ffOJp86BGHI-mUn6Rft-F2NDn4',
    appId: '1:381787096222:web:4fdb31dd98e26f3a5b278f',
    messagingSenderId: '381787096222',
    projectId: 'flash-chat-8ac0f',
    authDomain: 'flash-chat-8ac0f.firebaseapp.com',
    storageBucket: 'flash-chat-8ac0f.appspot.com',
    measurementId: 'G-XWK2P49HS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ZHS0uoTRVtgL9vp38ndbpqN3FHh5kyg',
    appId: '1:381787096222:android:5d66a0a8554cee805b278f',
    messagingSenderId: '381787096222',
    projectId: 'flash-chat-8ac0f',
    storageBucket: 'flash-chat-8ac0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBty7UFnZQLRVh1gkmXq-1zPo-E65Gvufs',
    appId: '1:381787096222:ios:fa63a5d183d8d4845b278f',
    messagingSenderId: '381787096222',
    projectId: 'flash-chat-8ac0f',
    storageBucket: 'flash-chat-8ac0f.appspot.com',
    iosClientId: '381787096222-3tdic24tnm2c2gop72d2pepe9k8mrobq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
